### ISSUE TITLE
[bug] unknown attribute error on selected news heading in trending section.

### ISSUE THREAD

**Issue by Shivani-Padhye** [fafadiatech/newscout_web#457] opened 2020-04-13 05:15 UTC
Have a look at this news.It is throwing attribute error.
This news is listed in trending section.
URL:http://www.newscout.in/news/article/michael-avenatti-granted-90-day-release-from-manhattan-jail-after-raising-concerns-about-coronavirus-1520249/

![Screenshot from 2020-04-13 10-44-43](https://user-images.githubusercontent.com/57176686/79094038-d0710400-7d73-11ea-8a76-90a07e395d5e.png)

**Comment by sidharthshah** [comment] 2020-04-13 06:18
Duplicate of issue #454, for now closing this issue

**Closed by sidharthshah** 2020-04-13 06:18 UTC
Labels: duplicate
